version: '3.8'

services:
  dispatcher:
    build:
      context: ./dispatcher
    ports:
      - "8000:8000"
    depends_on:
      - worker_arith
      - worker_symbolic

  worker_arith:
    build:
      context: ./worker_arith
    ports:
      - "8001:8000"

  worker_symbolic:
    build:
      context: ./worker_symbolic
    ports:
      - "8002:8000"
